# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kinect_bridge2/KinectSpeech.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kinect_bridge2.msg

class KinectSpeech(genpy.Message):
  _md5sum = "bb4474b86bf47d9228f16d2febb29bc8"
  _type = "kinect_bridge2/KinectSpeech"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """kinect_bridge2/KinectSpeechPhrase[] phrases

================================================================================
MSG: kinect_bridge2/KinectSpeechPhrase
string tag
float32 confidence

"""
  __slots__ = ['phrases']
  _slot_types = ['kinect_bridge2/KinectSpeechPhrase[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       phrases

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KinectSpeech, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.phrases is None:
        self.phrases = []
    else:
      self.phrases = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.phrases)
      buff.write(_struct_I.pack(length))
      for val1 in self.phrases:
        _x = val1.tag
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_f.pack(val1.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.phrases is None:
        self.phrases = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.phrases = []
      for i in range(0, length):
        val1 = kinect_bridge2.msg.KinectSpeechPhrase()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.tag = str[start:end].decode('utf-8')
        else:
          val1.tag = str[start:end]
        start = end
        end += 4
        (val1.confidence,) = _struct_f.unpack(str[start:end])
        self.phrases.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.phrases)
      buff.write(_struct_I.pack(length))
      for val1 in self.phrases:
        _x = val1.tag
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_f.pack(val1.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.phrases is None:
        self.phrases = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.phrases = []
      for i in range(0, length):
        val1 = kinect_bridge2.msg.KinectSpeechPhrase()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.tag = str[start:end].decode('utf-8')
        else:
          val1.tag = str[start:end]
        start = end
        end += 4
        (val1.confidence,) = _struct_f.unpack(str[start:end])
        self.phrases.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_f = struct.Struct("<f")
