/* Auto-generated by genmsg_cpp for file /home/vadim/Desktop/workspace/kinect_bridge2/msg/KinectSpeechPhrase.msg */
#ifndef KINECT_BRIDGE2_MESSAGE_KINECTSPEECHPHRASE_H
#define KINECT_BRIDGE2_MESSAGE_KINECTSPEECHPHRASE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kinect_bridge2
{
template <class ContainerAllocator>
struct KinectSpeechPhrase_ {
  typedef KinectSpeechPhrase_<ContainerAllocator> Type;

  KinectSpeechPhrase_()
  : tag()
  , confidence(0.0)
  {
  }

  KinectSpeechPhrase_(const ContainerAllocator& _alloc)
  : tag(_alloc)
  , confidence(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tag_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  tag;

  typedef float _confidence_type;
  float confidence;


  typedef boost::shared_ptr< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator>  const> ConstPtr;
}; // struct KinectSpeechPhrase
typedef  ::kinect_bridge2::KinectSpeechPhrase_<std::allocator<void> > KinectSpeechPhrase;

typedef boost::shared_ptr< ::kinect_bridge2::KinectSpeechPhrase> KinectSpeechPhrasePtr;
typedef boost::shared_ptr< ::kinect_bridge2::KinectSpeechPhrase const> KinectSpeechPhraseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kinect_bridge2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d43fa116b23bb95f464029ea5c22924";
  }

  static const char* value(const  ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5d43fa116b23bb95ULL;
  static const uint64_t static_value2 = 0xf464029ea5c22924ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kinect_bridge2/KinectSpeechPhrase";
  }

  static const char* value(const  ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string tag\n\
float32 confidence\n\
\n\
";
  }

  static const char* value(const  ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.tag);
    stream.next(m.confidence);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KinectSpeechPhrase_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kinect_bridge2::KinectSpeechPhrase_<ContainerAllocator> & v) 
  {
    s << indent << "tag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tag);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KINECT_BRIDGE2_MESSAGE_KINECTSPEECHPHRASE_H

